### ISSUE TITLE
Ability to generate and pack version list and crcs ? 

### ISSUE THREAD

**Issue by Graviton1647** [Displee/rs-cache-library#32]
Ability to run a function that generates and packs crcs and version lists

**Comment by Displee** [comment]
Hmm. I'm assuming you're talking about archives with a custom name?

**Comment by Graviton1647** [comment]
Yes files with custom names :)

**Comment by Displee** [comment]
Alright. So there are normally 3 custom files. I assume you only need 2 custom files right (crc and version).

**Comment by Graviton1647** [comment]
Yes

**Comment by Displee** [comment]
I've created a function where you should be able to add version and crc files in #35 using the following code:
```kotlin
Index317.addMetaFiles("version_file", "crc_file")
```
This method needs to be executed before you create the cache library object.
